name: Vuepress Build

# Controls when the action will run.
on:
  push:
    branches:
      - "**" # matches every branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
