# This is a basic workflow to help you get started with Actions

name: Code Linting

# Controls when the action will run.
on:
  push:
    branches:
      - "**" # matches every branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@latest
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
